CREATE TABLE Users (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserName NVARCHAR(100) NOT NULL,
  Email NVARCHAR(256) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(256) NOT NULL,
  CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Images (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL,
  Title NVARCHAR(200) NOT NULL,
  Tag NVARCHAR(80) NOT NULL,
  Platform NVARCHAR(150) NOT NULL,
  Description NVARCHAR(2000) NOT NULL,
  Prompt NVARCHAR(4000) NOT NULL,
  BlobUrl NVARCHAR(1000) NOT NULL,
  CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Images_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Comments (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  ImageId INT NOT NULL,
  UserId INT NOT NULL,
  Content NVARCHAR(1000) NOT NULL,
  CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Comments_Images FOREIGN KEY (ImageId) REFERENCES Images(Id) ON DELETE CASCADE,
  CONSTRAINT FK_Comments_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Likes (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  ImageId INT NOT NULL,
  UserId INT NOT NULL,
  CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Likes_Images FOREIGN KEY (ImageId) REFERENCES Images(Id) ON DELETE CASCADE,
  CONSTRAINT FK_Likes_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
  CONSTRAINT UQ_Likes_ImageUser UNIQUE (ImageId, UserId)
);

CREATE INDEX IX_Images_CreatedAtUtc ON Images (CreatedAtUtc DESC);
CREATE INDEX IX_Images_Tag ON Images (Tag);
CREATE INDEX IX_Comments_ImageId ON Comments (ImageId);
